export const TERMINAL_APPLICATION_STATUSES = ['REJECTED', 'CLOSED', 'DISBURSED'] as const;

export const SANCTIONED_PLUS_STATUSES = ['SANCTIONED', 'DISBURSED', 'CLOSED'] as const;

export const ELIGIBILITY_ENGINE_VERSION = 'los-eligibility-v1.0';

export const STATUS_TRANSITIONS: Record<string, string[]> = {
  DRAFT: ['SUBMITTED', 'CLOSED'],
  SUBMITTED: ['UNDER_REVIEW', 'DOCUMENT_PENDING', 'REJECTED', 'CLOSED'],
  UNDER_REVIEW: ['DOCUMENT_PENDING', 'BANK_LOGIN', 'CREDIT_REVIEW', 'REJECTED'],
  DOCUMENT_PENDING: ['UNDER_REVIEW', 'BANK_LOGIN', 'CREDIT_REVIEW', 'REJECTED'],
  BANK_LOGIN: ['CREDIT_REVIEW', 'REJECTED'],
  CREDIT_REVIEW: ['SANCTIONED', 'REJECTED', 'DOCUMENT_PENDING'],
  SANCTIONED: ['DISBURSED', 'REJECTED', 'CLOSED'],
  DISBURSED: ['CLOSED'],
  REJECTED: ['CLOSED'],
  CLOSED: [],
};
