module.exports = {
  apps: [
    {
      name: 'kuberone-api',
      script: './apps/backend/dist/server.js',
      cwd: '/opt/kuberone',
      instances: 'max',
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env_uat: {
        NODE_ENV: 'production',
        APP_ENV: 'uat',
        API_WORKERS_ENABLED: 'false',
      },
      env_staging: {
        NODE_ENV: 'production',
        APP_ENV: 'staging',
        API_WORKERS_ENABLED: 'false',
      },
      env_production: {
        NODE_ENV: 'production',
        APP_ENV: 'production',
        API_WORKERS_ENABLED: 'false',
      },
      error_file: '/var/log/kuberone/api-error.log',
      out_file: '/var/log/kuberone/api-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'kuberone-worker',
      script: './apps/backend/dist/server.js',
      cwd: '/opt/kuberone',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '768M',
      env_production: {
        NODE_ENV: 'production',
        APP_ENV: 'production',
        API_WORKERS_ENABLED: 'true',
      },
      error_file: '/var/log/kuberone/worker-error.log',
      out_file: '/var/log/kuberone/worker-out.log',
      merge_logs: true,
      time: true,
    },
  ],
};
