import type { PrismaClient } from '@prisma/client';

const TEMPLATES = [
  {
    code: 'LEAD_NURTURE_EMAIL',
    name: 'Lead Nurture Email',
    contentType: 'EMAIL' as const,
    category: 'sales',
    tone: 'PREMIUM_FINTECH' as const,
    language: 'EN' as const,
    systemPrompt: 'You are a premium fintech copywriter for Kuber Finserve. Write compliant, personalized loan nurture emails.',
    userPrompt: 'Write a nurture email for {{customerName}} interested in {{product}}. Loan amount: {{loanAmount}}. Tone: helpful, premium.',
    variables: { customerName: 'string', product: 'string', loanAmount: 'number' },
  },
  {
    code: 'APPLICATION_FOLLOWUP_SMS',
    name: 'Application Follow-up SMS',
    contentType: 'SMS' as const,
    category: 'sales',
    tone: 'FRIENDLY' as const,
    language: 'EN' as const,
    systemPrompt: 'Write concise SMS under 160 characters for Kuber Finserve loan applications.',
    userPrompt: 'Remind {{customerName}} to complete application {{applicationStatus}}. Include KuberOne link.',
    variables: { customerName: 'string', applicationStatus: 'string' },
  },
  {
    code: 'SUPPORT_REPLY',
    name: 'Support Ticket Reply',
    contentType: 'SUPPORT_RESPONSE' as const,
    category: 'support',
    tone: 'SUPPORT' as const,
    language: 'EN' as const,
    systemPrompt: 'You are a Kuber Finserve support specialist. Be empathetic, accurate, and policy-aligned.',
    userPrompt: 'Draft a support reply for ticket about: {{prompt}}. Reference policies and next steps.',
    variables: { prompt: 'string' },
  },
  {
    code: 'SALES_CALL_SCRIPT',
    name: 'Sales Call Script',
    contentType: 'CALL_SCRIPT' as const,
    category: 'sales',
    tone: 'SALES' as const,
    language: 'HINGLISH' as const,
    systemPrompt: 'Write natural Hinglish call scripts for DSA/sales teams at Kuber Finserve.',
    userPrompt: 'Call script for {{product}} lead with score {{leadScore}} in {{region}}.',
    variables: { product: 'string', leadScore: 'number', region: 'string' },
  },
  {
    code: 'REFERRAL_CAMPAIGN_WHATSAPP',
    name: 'Referral Campaign WhatsApp',
    contentType: 'WHATSAPP' as const,
    category: 'marketing',
    tone: 'PROMOTIONAL' as const,
    language: 'HI' as const,
    systemPrompt: 'Write WhatsApp marketing messages in Hindi for referral campaigns. Compliant with RBI guidelines.',
    userPrompt: 'Referral invite for {{customerName}}. Campaign: {{campaignType}}.',
    variables: { customerName: 'string', campaignType: 'string' },
  },
  {
    code: 'ONBOARDING_PUSH',
    name: 'Customer Onboarding Push',
    contentType: 'PUSH' as const,
    category: 'onboarding',
    tone: 'FRIENDLY' as const,
    language: 'EN' as const,
    systemPrompt: 'Write short push notification copy for KuberOne mobile app onboarding.',
    userPrompt: 'Welcome push for {{customerName}} starting {{product}} journey.',
    variables: { customerName: 'string', product: 'string' },
  },
  {
    code: 'KB_ARTICLE_DRAFT',
    name: 'Knowledge Article Draft',
    contentType: 'KNOWLEDGE_ARTICLE' as const,
    category: 'knowledge',
    tone: 'PROFESSIONAL' as const,
    language: 'EN' as const,
    systemPrompt: 'Write structured knowledge base articles with headings, FAQs, and compliance notes for Kuber Finserve.',
    userPrompt: 'Article about: {{prompt}}. Include policy references.',
    variables: { prompt: 'string' },
  },
  {
    code: 'COMMISSION_PAYOUT_EMAIL',
    name: 'Commission Payout Email',
    contentType: 'COMMISSION_COMMUNICATION' as const,
    category: 'finance',
    tone: 'FORMAL' as const,
    language: 'EN' as const,
    systemPrompt: 'Write formal commission payout communications for DSA partners.',
    userPrompt: 'Commission payout notification for partner {{partnerType}} in {{branch}}.',
    variables: { partnerType: 'string', branch: 'string' },
  },
];

export async function seedContent(prisma: PrismaClient): Promise<void> {
  for (const template of TEMPLATES) {
    await prisma.contentTemplate.upsert({
      where: { code: template.code },
      update: {
        name: template.name,
        contentType: template.contentType,
        category: template.category,
        tone: template.tone,
        language: template.language,
        systemPrompt: template.systemPrompt,
        userPrompt: template.userPrompt,
        variables: template.variables,
        isActive: true,
      },
      create: {
        code: template.code,
        name: template.name,
        contentType: template.contentType,
        category: template.category,
        tone: template.tone,
        language: template.language,
        systemPrompt: template.systemPrompt,
        userPrompt: template.userPrompt,
        variables: template.variables,
        isActive: true,
      },
    });
  }

  console.log('  → content templates seeded');
}
