import type { PrismaClient } from '@prisma/client';

const PERMISSIONS = [
  { code: 'auth.login', name: 'Login', module: 'auth' },
  { code: 'users.read', name: 'View Users', module: 'users' },
  { code: 'users.write', name: 'Manage Users', module: 'users' },
  { code: 'roles.read', name: 'View Roles', module: 'roles' },
  { code: 'roles.write', name: 'Manage Roles', module: 'roles' },
  { code: 'permissions.read', name: 'View Permissions', module: 'permissions' },
  { code: 'permissions.write', name: 'Manage Permissions', module: 'permissions' },
  { code: 'rbac.read', name: 'View RBAC Assignments', module: 'rbac' },
  { code: 'rbac.configure', name: 'Configure RBAC', module: 'rbac' },
  { code: 'leads.read', name: 'View Leads', module: 'leads' },
  { code: 'leads.write', name: 'Manage Leads', module: 'leads' },
  { code: 'leads.assign', name: 'Assign Leads', module: 'leads' },
  { code: 'leads.export', name: 'Export Leads', module: 'leads' },
  { code: 'leads.approve', name: 'Approve Leads', module: 'leads' },
  { code: 'customers.read', name: 'View Customers', module: 'customers' },
  { code: 'customers.write', name: 'Manage Customers', module: 'customers' },
  { code: 'kyc.read', name: 'View KYC', module: 'kyc' },
  { code: 'kyc.write', name: 'Manage KYC', module: 'kyc' },
  { code: 'applications.read', name: 'View Applications', module: 'applications' },
  { code: 'applications.write', name: 'Manage Applications', module: 'applications' },
  { code: 'applications.assign', name: 'Assign Applications', module: 'applications' },
  { code: 'applications.approve', name: 'Approve Applications', module: 'applications' },
  { code: 'applications.disburse', name: 'Disburse Applications', module: 'applications' },
  { code: 'documents.read', name: 'View Documents', module: 'documents' },
  { code: 'documents.write', name: 'Manage Documents', module: 'documents' },
  { code: 'documents.verify', name: 'Verify Documents', module: 'documents' },
  { code: 'documents.approve', name: 'Approve Documents', module: 'documents' },
  { code: 'documents.download', name: 'Download Documents', module: 'documents' },
  { code: 'partners.read', name: 'View Partners', module: 'partners' },
  { code: 'partners.write', name: 'Manage Partners', module: 'partners' },
  { code: 'commissions.read', name: 'View Commissions', module: 'commissions' },
  { code: 'commissions.write', name: 'Manage Commissions', module: 'commissions' },
  { code: 'commissions.approve', name: 'Approve Commissions', module: 'commissions' },
  { code: 'commissions.pay', name: 'Release Commission Payouts', module: 'commissions' },
  { code: 'commissions.recover', name: 'Recover Commissions', module: 'commissions' },
  { code: 'analytics.read', name: 'View Analytics', module: 'analytics' },
  { code: 'analytics.export', name: 'Export Analytics', module: 'analytics' },
  { code: 'analytics.configure', name: 'Configure Analytics', module: 'analytics' },
  { code: 'executive_analytics.read', name: 'View Executive Analytics', module: 'executive_analytics' },
  { code: 'executive_analytics.team', name: 'View Team Executive Analytics', module: 'executive_analytics' },
  { code: 'executive_analytics.export', name: 'Export Executive Analytics', module: 'executive_analytics' },
  { code: 'executive_analytics.manage', name: 'Manage Executive Targets', module: 'executive_analytics' },
  { code: 'branch_analytics.read', name: 'View Branch Analytics', module: 'branch_analytics' },
  { code: 'branch_analytics.region', name: 'View Regional Branch Analytics', module: 'branch_analytics' },
  { code: 'branch_analytics.export', name: 'Export Branch Analytics', module: 'branch_analytics' },
  { code: 'branch_analytics.manage', name: 'Manage Branch Targets', module: 'branch_analytics' },
  { code: 'regional_analytics.read', name: 'View Regional Analytics', module: 'regional_analytics' },
  { code: 'regional_analytics.all', name: 'View All Regional Analytics', module: 'regional_analytics' },
  { code: 'regional_analytics.export', name: 'Export Regional Analytics', module: 'regional_analytics' },
  { code: 'regional_analytics.manage', name: 'Manage Regional Targets', module: 'regional_analytics' },
  { code: 'lead_scoring.read', name: 'View Lead Scoring', module: 'lead_scoring' },
  { code: 'lead_scoring.write', name: 'Run Lead Scoring', module: 'lead_scoring' },
  { code: 'lead_scoring.configure', name: 'Configure Lead Scoring', module: 'lead_scoring' },
  { code: 'recommendations.read', name: 'View AI Recommendations', module: 'recommendations' },
  { code: 'recommendations.configure', name: 'Configure Recommendation Rules', module: 'recommendations' },
  { code: 'knowledge.read', name: 'View Knowledge Base', module: 'knowledge' },
  { code: 'knowledge.write', name: 'Create & Edit Articles', module: 'knowledge' },
  { code: 'knowledge.review', name: 'Review Knowledge Articles', module: 'knowledge' },
  { code: 'knowledge.approve', name: 'Approve Knowledge Articles', module: 'knowledge' },
  { code: 'knowledge.publish', name: 'Publish Knowledge Articles', module: 'knowledge' },
  { code: 'knowledge.manage', name: 'Manage Knowledge Base', module: 'knowledge' },
  { code: 'rag.read', name: 'Use RAG Retrieval', module: 'rag' },
  { code: 'rag.write', name: 'Ingest RAG Documents', module: 'rag' },
  { code: 'rag.manage', name: 'Manage RAG Pipeline', module: 'rag' },
  { code: 'copilot.read', name: 'Use AI Sales Copilot', module: 'copilot' },
  { code: 'ai.read', name: 'Use AI Platform', module: 'ai' },
  { code: 'ai.write', name: 'Execute AI Operations', module: 'ai' },
  { code: 'ai.manage', name: 'Manage AI Platform', module: 'ai' },
  { code: 'settings.read', name: 'View Settings', module: 'settings' },
  { code: 'settings.write', name: 'Manage Settings', module: 'settings' },
  { code: 'audit.read', name: 'View Audit Logs', module: 'audit' },
  { code: 'audit.export', name: 'Export Audit Logs', module: 'audit' },
  { code: 'compliance.read', name: 'View Compliance Center', module: 'compliance' },
  { code: 'compliance.manage', name: 'Manage Compliance Rules', module: 'compliance' },
  { code: 'risk.read', name: 'View Risk Management', module: 'risk' },
  { code: 'risk.manage', name: 'Manage Risk Register', module: 'risk' },
  { code: 'security.read', name: 'View Security Center', module: 'security' },
  { code: 'security.manage', name: 'Manage Security Alerts', module: 'security' },
  { code: 'products.read', name: 'View Products', module: 'products' },
  { code: 'products.write', name: 'Manage Products', module: 'products' },
  { code: 'products.approve', name: 'Approve Products', module: 'products' },
  { code: 'products.configure', name: 'Configure Products', module: 'products' },
  { code: 'lenders.read', name: 'View Lenders', module: 'lenders' },
  { code: 'lenders.write', name: 'Manage Lenders', module: 'lenders' },
  { code: 'eligibility.read', name: 'View Eligibility Rules', module: 'eligibility' },
  { code: 'eligibility.write', name: 'Manage Eligibility Rules', module: 'eligibility' },
  { code: 'emi.read', name: 'Use EMI Calculator', module: 'emi' },
  { code: 'referrals.read', name: 'View Referrals', module: 'referrals' },
  { code: 'referrals.write', name: 'Manage Referrals', module: 'referrals' },
  { code: 'referrals.approve', name: 'Approve Referral Rewards', module: 'referrals' },
  { code: 'notifications.read', name: 'View Notifications', module: 'notifications' },
  { code: 'notifications.write', name: 'Manage Notifications', module: 'notifications' },
  { code: 'notifications.send', name: 'Send Notifications', module: 'notifications' },
  { code: 'notifications.configure', name: 'Configure Notification Templates', module: 'notifications' },
  { code: 'emails.read', name: 'View Emails', module: 'emails' },
  { code: 'emails.send', name: 'Send Emails', module: 'emails' },
  { code: 'emails.configure', name: 'Configure Email Templates & Providers', module: 'emails' },
  { code: 'emails.analytics', name: 'View Email Analytics', module: 'emails' },
  { code: 'sms.read', name: 'View SMS', module: 'sms' },
  { code: 'sms.send', name: 'Send SMS', module: 'sms' },
  { code: 'sms.configure', name: 'Configure SMS Templates & Providers', module: 'sms' },
  { code: 'sms.analytics', name: 'View SMS Analytics', module: 'sms' },
  { code: 'push.read', name: 'View Push Notifications', module: 'push' },
  { code: 'push.send', name: 'Send Push Notifications', module: 'push' },
  { code: 'push.configure', name: 'Configure Push Templates & Providers', module: 'push' },
  { code: 'push.analytics', name: 'View Push Analytics', module: 'push' },
  { code: 'campaigns.read', name: 'View Campaigns', module: 'campaigns' },
  { code: 'campaigns.write', name: 'Manage Campaigns', module: 'campaigns' },
  { code: 'employees.read', name: 'View Employees', module: 'employees' },
  { code: 'employees.write', name: 'Manage Employees', module: 'employees' },
  { code: 'branches.read', name: 'View Branches', module: 'branches' },
  { code: 'branches.write', name: 'Manage Branches', module: 'branches' },
  { code: 'tickets.read', name: 'View Tickets', module: 'tickets' },
  { code: 'tickets.write', name: 'Manage Tickets', module: 'tickets' },
  { code: 'tickets.assign', name: 'Assign Tickets', module: 'tickets' },
  { code: 'tickets.resolve', name: 'Resolve Tickets', module: 'tickets' },
  { code: 'tickets.close', name: 'Close Tickets', module: 'tickets' },
  { code: 'tickets.escalate', name: 'Escalate Tickets', module: 'tickets' },
  { code: 'automation.read', name: 'View Marketing Automation', module: 'automation' },
  { code: 'automation.write', name: 'Manage Automation Workflows', module: 'automation' },
  { code: 'automation.approve', name: 'Approve Automation Workflows', module: 'automation' },
  { code: 'automation.execute', name: 'Execute Automation Journeys', module: 'automation' },
  { code: 'automation.analytics', name: 'View Automation Analytics', module: 'automation' },
  { code: 'automation.manage', name: 'Manage Automation Platform', module: 'automation' },
  { code: 'content.read', name: 'View AI Content', module: 'content' },
  { code: 'content.write', name: 'Generate AI Content', module: 'content' },
  { code: 'content.approve', name: 'Approve AI Content', module: 'content' },
  { code: 'content.publish', name: 'Publish AI Content', module: 'content' },
  { code: 'content.analytics', name: 'View Content Analytics', module: 'content' },
  { code: 'content.manage', name: 'Manage Content Platform', module: 'content' },
  { code: 'uat.read', name: 'View UAT Framework', module: 'uat' },
  { code: 'uat.write', name: 'Manage UAT Plans & Test Cases', module: 'uat' },
  { code: 'uat.execute', name: 'Execute UAT Test Cases', module: 'uat' },
  { code: 'uat.approve', name: 'Approve UAT Defects & Cycles', module: 'uat' },
  { code: 'uat.review', name: 'Review UAT Signoff Areas', module: 'uat' },
  { code: 'uat.signoff', name: 'UAT Business Signoff', module: 'uat' },
  { code: 'monitoring.read', name: 'View Production Monitoring', module: 'monitoring' },
  { code: 'monitoring.manage', name: 'Manage Monitoring Platform', module: 'monitoring' },
  { code: 'monitoring.alerts', name: 'Manage Monitoring Alerts', module: 'monitoring' },
  { code: 'observability.read', name: 'View Observability Platform', module: 'observability' },
  { code: 'observability.manage', name: 'Manage Observability Platform', module: 'observability' },
  { code: 'logs.read', name: 'View Application Logs', module: 'observability' },
  { code: 'traces.read', name: 'View Distributed Traces', module: 'observability' },
  { code: 'errors.read', name: 'View Error Tracking', module: 'errors' },
  { code: 'errors.manage', name: 'Manage Error Tracking', module: 'errors' },
  { code: 'errors.assign', name: 'Assign Errors', module: 'errors' },
  { code: 'errors.resolve', name: 'Resolve Errors', module: 'errors' },
  { code: 'errors.analytics', name: 'View Error Analytics', module: 'errors' },
  { code: 'backup.read', name: 'View Backup & Recovery', module: 'backup' },
  { code: 'backup.manage', name: 'Manage Backup Jobs', module: 'backup' },
  { code: 'backup.restore', name: 'Execute Restores', module: 'backup' },
  { code: 'dr.read', name: 'View Disaster Recovery', module: 'backup' },
  { code: 'dr.manage', name: 'Manage DR Drills', module: 'backup' },
  { code: 'dr.execute', name: 'Execute DR Procedures', module: 'dr' },
  { code: 'recovery.manage', name: 'Manage Recovery Operations', module: 'dr' },
  { code: 'devops.read', name: 'View DevOps Dashboard', module: 'devops' },
  { code: 'devops.deploy', name: 'Trigger Deployments', module: 'devops' },
  { code: 'devops.rollback', name: 'Execute Rollbacks', module: 'devops' },
  { code: 'devops.manage', name: 'Manage Releases & Pipelines', module: 'devops' },
  { code: 'infrastructure.read', name: 'View Infrastructure', module: 'infrastructure' },
  { code: 'infrastructure.manage', name: 'Manage Infrastructure', module: 'infrastructure' },
  { code: 'deployment.manage', name: 'Manage Deployments', module: 'infrastructure' },
  { code: 'staging.read', name: 'View Staging Environment', module: 'staging' },
  { code: 'staging.manage', name: 'Manage Staging Environment', module: 'staging' },
  { code: 'release.manage', name: 'Manage Release Validation', module: 'staging' },
  { code: 'production.read', name: 'View Production Environment', module: 'production' },
  { code: 'production.manage', name: 'Manage Production Environment', module: 'production' },
  { code: 'mobile.release', name: 'View Mobile Releases', module: 'mobile' },
  { code: 'mobile.build', name: 'Trigger Mobile Builds', module: 'mobile' },
  { code: 'mobile.publish', name: 'Publish to App Stores', module: 'mobile' },
  { code: 'backend.deploy', name: 'Deploy Backend to Production', module: 'backend_deployment' },
  { code: 'backend.release', name: 'Manage Backend Releases', module: 'backend_deployment' },
  { code: 'backend.manage', name: 'Manage Backend Deployment Platform', module: 'backend_deployment' },
  { code: 'golive.read', name: 'View Go-Live Checklist', module: 'go_live' },
  { code: 'golive.manage', name: 'Manage Go-Live Checklist', module: 'go_live' },
  { code: 'golive.approve', name: 'Approve Go-Live Gates', module: 'go_live' },
  { code: 'release.approve', name: 'Final Release Approval', module: 'go_live' },
  { code: 'launch.read', name: 'View Go-Live Command Center', module: 'go_live' },
  { code: 'launch.manage', name: 'Manage Launch Execution', module: 'go_live' },
  { code: 'launch.approve', name: 'Approve Launch Steps', module: 'go_live' },
  { code: 'incident.manage', name: 'Manage Launch Incidents', module: 'go_live' },
  { code: 'hypercare.read', name: 'View Hypercare Dashboard', module: 'hypercare' },
  { code: 'hypercare.manage', name: 'Manage Hypercare Issues & Metrics', module: 'hypercare' },
  { code: 'hypercare.resolve', name: 'Resolve Hypercare Incidents & Issues', module: 'hypercare' },
];

export async function seedPermissions(prisma: PrismaClient): Promise<void> {
  for (const permission of PERMISSIONS) {
    await prisma.permission.upsert({
      where: { code: permission.code },
      update: { name: permission.name, module: permission.module },
      create: permission,
    });
  }

  console.log('  → permissions seeded');
}
