import type { PrismaClient } from '@prisma/client';

type RoleMatrix = Record<string, string[]>;

const ROLE_PERMISSION_MATRIX: RoleMatrix = {
  SUPER_ADMIN: ['*'],
  ADMIN: ['*'],
  MANAGEMENT: [
    'auth.login',
    'users.read',
    'roles.read',
    'permissions.read',
    'rbac.read',
    'customers.read',
    'leads.read',
    'leads.export',
    'applications.read',
    'documents.read',
    'documents.download',
    'kyc.read',
    'products.read',
    'lenders.read',
    'eligibility.read',
    'emi.read',
    'referrals.read',
    'commissions.read',
    'commissions.approve',
    'notifications.read',
    'analytics.read',
    'analytics.export',
    'analytics.configure',
    'executive_analytics.read',
    'executive_analytics.team',
    'executive_analytics.export',
    'executive_analytics.manage',
    'branch_analytics.read',
    'branch_analytics.region',
    'branch_analytics.export',
    'branch_analytics.manage',
    'regional_analytics.read',
    'regional_analytics.all',
    'regional_analytics.export',
    'regional_analytics.manage',
    'copilot.read',
    'audit.read',
    'settings.read',
    'tickets.read',
    'knowledge.read',
    'knowledge.write',
    'knowledge.review',
    'knowledge.approve',
    'knowledge.publish',
    'knowledge.manage',
    'rag.read',
    'rag.write',
    'rag.manage',
    'ai.read',
    'ai.write',
    'ai.manage',
    'lead_scoring.read',
    'lead_scoring.write',
    'lead_scoring.configure',
    'recommendations.read',
    'recommendations.configure',
  ],
  COMPLIANCE_MANAGER: [
    'auth.login',
    'customers.read',
    'applications.read',
    'documents.read',
    'documents.verify',
    'documents.approve',
    'documents.download',
    'kyc.read',
    'kyc.write',
    'audit.read',
    'referrals.read',
    'commissions.read',
    'notifications.read',
    'knowledge.read',
    'rag.read',
    'rag.manage',
    'ai.read',
    'ai.manage',
  ],
  REGIONAL_MANAGER: [
    'auth.login',
    'users.read',
    'customers.read',
    'customers.write',
    'leads.read',
    'leads.write',
    'leads.assign',
    'leads.export',
    'leads.approve',
    'applications.read',
    'applications.write',
    'applications.assign',
    'applications.approve',
    'documents.read',
    'documents.write',
    'documents.download',
    'kyc.read',
    'products.read',
    'referrals.read',
    'referrals.approve',
    'commissions.read',
    'commissions.approve',
    'partners.read',
    'analytics.read',
    'executive_analytics.read',
    'executive_analytics.team',
    'executive_analytics.export',
    'branch_analytics.read',
    'branch_analytics.region',
    'branch_analytics.export',
    'regional_analytics.read',
    'regional_analytics.export',
    'copilot.read',
    'recommendations.read',
    'recommendations.configure',
    'lead_scoring.read',
    'lead_scoring.write',
    'knowledge.read',
    'rag.read',
    'notifications.read',
    'audit.read',
  ],
  BRANCH_MANAGER: [
    'auth.login',
    'users.read',
    'customers.read',
    'customers.write',
    'leads.read',
    'leads.write',
    'leads.assign',
    'leads.export',
    'applications.read',
    'applications.write',
    'applications.assign',
    'applications.approve',
    'documents.read',
    'documents.write',
    'documents.verify',
    'documents.download',
    'kyc.read',
    'products.read',
    'referrals.read',
    'commissions.read',
    'partners.read',
    'analytics.read',
    'executive_analytics.read',
    'executive_analytics.team',
    'executive_analytics.export',
    'branch_analytics.read',
    'branch_analytics.export',
    'copilot.read',
    'recommendations.read',
    'recommendations.configure',
    'lead_scoring.read',
    'lead_scoring.write',
    'knowledge.read',
    'rag.read',
    'notifications.read',
    'audit.read',
  ],
  RELATIONSHIP_MANAGER: [
    'auth.login',
    'customers.read',
    'customers.write',
    'leads.read',
    'leads.write',
    'leads.assign',
    'applications.read',
    'applications.write',
    'documents.read',
    'documents.write',
    'documents.download',
    'kyc.read',
    'kyc.write',
    'products.read',
    'emi.read',
    'eligibility.read',
    'referrals.read',
    'copilot.read',
    'recommendations.read',
    'knowledge.read',
    'knowledge.write',
    'rag.read',
    'rag.write',
    'lead_scoring.read',
    'lead_scoring.write',
    'notifications.read',
    'executive_analytics.read',
  ],
  SALES_EXECUTIVE: [
    'auth.login',
    'customers.read',
    'customers.write',
    'leads.read',
    'leads.write',
    'leads.assign',
    'applications.read',
    'applications.write',
    'documents.read',
    'documents.write',
    'documents.download',
    'kyc.read',
    'products.read',
    'emi.read',
    'eligibility.read',
    'referrals.read',
    'copilot.read',
    'recommendations.read',
    'knowledge.read',
    'knowledge.write',
    'rag.read',
    'rag.write',
    'lead_scoring.read',
    'lead_scoring.write',
    'notifications.read',
    'executive_analytics.read',
  ],
  CREDIT_EXECUTIVE: [
    'auth.login',
    'customers.read',
    'applications.read',
    'applications.approve',
    'documents.read',
    'documents.verify',
    'documents.approve',
    'documents.download',
    'kyc.read',
    'products.read',
    'lenders.read',
    'eligibility.read',
    'copilot.read',
    'recommendations.read',
    'knowledge.read',
    'knowledge.write',
    'rag.read',
    'rag.write',
    'lead_scoring.read',
    'lead_scoring.write',
    'notifications.read',
    'audit.read',
    'executive_analytics.read',
  ],
  CREDIT_ANALYST: [
    'auth.login',
    'customers.read',
    'applications.read',
    'documents.read',
    'documents.verify',
    'documents.download',
    'kyc.read',
    'products.read',
    'notifications.read',
    'executive_analytics.read',
  ],
  OPERATIONS_EXECUTIVE: [
    'auth.login',
    'customers.read',
    'applications.read',
    'applications.write',
    'applications.disburse',
    'documents.read',
    'documents.write',
    'documents.download',
    'kyc.read',
    'commissions.read',
    'commissions.write',
    'copilot.read',
    'recommendations.read',
    'knowledge.read',
    'knowledge.write',
    'rag.read',
    'rag.write',
    'lead_scoring.read',
    'lead_scoring.write',
    'notifications.read',
    'executive_analytics.read',
  ],
  OPS_EXECUTIVE: [
    'auth.login',
    'customers.read',
    'applications.read',
    'applications.write',
    'applications.disburse',
    'documents.read',
    'documents.write',
    'documents.download',
    'commissions.read',
    'notifications.read',
  ],
  SUPPORT: [
    'auth.login',
    'customers.read',
    'leads.read',
    'applications.read',
    'documents.read',
    'documents.download',
    'kyc.read',
    'knowledge.read',
    'rag.read',
    'ai.read',
    'notifications.read',
    'audit.read',
    'tickets.read',
    'tickets.write',
    'tickets.assign',
    'tickets.resolve',
    'tickets.close',
    'tickets.escalate',
  ],
  DSA_PARTNER: [
    'auth.login',
    'leads.read',
    'leads.write',
    'applications.read',
    'applications.write',
    'documents.read',
    'documents.write',
    'documents.download',
    'commissions.read',
    'referrals.read',
    'referrals.write',
    'notifications.read',
    'partners.read',
    'tickets.read',
    'tickets.write',
  ],
  CUSTOMER: [
    'auth.login',
    'customers.read',
    'customers.write',
    'applications.read',
    'applications.write',
    'documents.read',
    'documents.write',
    'documents.download',
    'kyc.read',
    'kyc.write',
    'emi.read',
    'eligibility.read',
    'referrals.read',
    'ai.read',
    'notifications.read',
    'tickets.read',
    'tickets.write',
  ],
};

export async function seedRolePermissions(prisma: PrismaClient): Promise<void> {
  const allPermissions = await prisma.permission.findMany();
  const permissionByCode = new Map(allPermissions.map((p) => [p.code, p.id]));

  for (const [roleCode, codes] of Object.entries(ROLE_PERMISSION_MATRIX)) {
    const role = await prisma.role.findUnique({ where: { code: roleCode } });
    if (!role) continue;

    const resolvedCodes = codes.includes('*') ? allPermissions.map((p) => p.code) : codes;

    for (const code of resolvedCodes) {
      const permissionId = permissionByCode.get(code);
      if (!permissionId) continue;

      await prisma.rolePermission.upsert({
        where: {
          roleId_permissionId: { roleId: role.id, permissionId },
        },
        update: {},
        create: { roleId: role.id, permissionId },
      });
    }
  }

  console.log('  → role-permissions seeded');
}
