import { type ReactNode } from 'react';

import { PermissionRoute } from '@/components/guards/PermissionRoute';

const PERMS: Record<string, string[] | undefined> = {
  dashboard: undefined,
  leads: ['leads.read'],
  'lead-scoring': ['lead_scoring.read'],
  customers: ['customers.read'],
  kyc: ['kyc.read', 'customers.read'],
  applications: ['applications.read'],
  documents: ['documents.read'],
  eligibility: ['eligibility.read'],
  emi: ['emi.read'],
  'voice-ai': ['eligibility.read', 'emi.read'],
  products: ['products.read'],
  partners: ['partners.read'],
  referrals: ['referrals.read'],
  commissions: ['commissions.read'],
  notifications: ['notifications.read'],
  email: ['emails.read', 'notifications.read'],
  sms: ['sms.read', 'notifications.read'],
  whatsapp: ['notifications.read'],
  push: ['push.read', 'notifications.read'],
  campaigns: ['campaigns.read', 'campaigns.write'],
  automation: ['automation.read', 'automation.write', 'automation.analytics'],
  content: ['content.read', 'content.write', 'content.analytics'],
  support: ['tickets.read'],
  copilot: ['copilot.read', 'leads.read', 'applications.read', 'analytics.read'],
  analytics: ['analytics.read'],
  management: ['executive_analytics.read', 'analytics.read', 'branch_analytics.read', 'regional_analytics.read'],
  'executive-analytics': ['executive_analytics.read', 'analytics.read'],
  'branch-analytics': ['branch_analytics.read', 'analytics.read'],
  'regional-analytics': ['regional_analytics.read', 'analytics.read'],
  recommendations: ['recommendations.read', 'analytics.read'],
  knowledge: ['knowledge.read', 'knowledge.write', 'knowledge.manage'],
  rag: ['rag.read', 'rag.write', 'rag.manage'],
  'ai-platform': ['ai.read', 'ai.write', 'ai.manage'],
  users: ['users.read', 'roles.read'],
  employees: ['employees.read', 'employees.write'],
  branches: ['branches.read', 'branches.write'],
  governance: ['audit.read', 'compliance.read', 'risk.read', 'security.read'],
  uat: ['uat.read', 'uat.write', 'uat.execute', 'uat.approve', 'uat.review', 'uat.signoff'],
  monitoring: ['monitoring.read', 'monitoring.manage', 'monitoring.alerts'],
  observability: ['observability.read', 'observability.manage', 'logs.read', 'traces.read'],
  errors: ['errors.read', 'errors.manage', 'errors.assign', 'errors.resolve', 'errors.analytics'],
  backup: ['backup.read', 'backup.manage', 'backup.restore', 'dr.read', 'dr.manage'],
  devops: ['devops.read', 'devops.deploy', 'devops.rollback', 'devops.manage'],
  infrastructure: ['infrastructure.read', 'infrastructure.manage', 'deployment.manage'],
  staging: ['staging.read', 'staging.manage', 'release.manage'],
  production: ['production.read', 'production.manage', 'deployment.manage', 'release.manage'],
  'go-live': ['golive.read', 'golive.manage', 'golive.approve', 'release.approve', 'launch.read', 'launch.manage', 'launch.approve', 'incident.manage', 'production.read'],
  hypercare: ['hypercare.read', 'hypercare.manage', 'hypercare.resolve', 'incident.manage', 'monitoring.read'],
  'mobile-releases': ['mobile.release', 'mobile.build', 'release.manage'],
  'play-store': ['mobile.release', 'mobile.publish', 'release.manage'],
  'app-store': ['mobile.release', 'mobile.publish', 'release.manage'],
  'backend-deployment': ['backend.deploy', 'backend.release', 'backend.manage', 'production.read', 'devops.deploy'],
  dr: ['dr.read', 'dr.manage', 'dr.execute', 'recovery.manage', 'backup.read'],
  audit: ['audit.read'],
  settings: ['settings.read', 'settings.write'],
  'developer-portal': ['settings.read', 'audit.read'],
};

export function withPermission(page: string, element: ReactNode): ReactNode {
  return <PermissionRoute permissions={PERMS[page]}>{element}</PermissionRoute>;
}
