export {
  createCustomerSchema,
  createCustomerAddressSchema,
  createCustomerConsentSchema,
  createCustomerEmploymentSchema,
  createCustomerIncomeSchema,
  customerIdQuerySchema,
  listCustomerAddressesQuerySchema,
  listCustomerConsentsQuerySchema,
  listCustomerEmploymentQuerySchema,
  listCustomerIncomeQuerySchema,
  listCustomersQuerySchema,
  updateCustomerSchema,
  updateCustomerAddressSchema,
  updateCustomerEmploymentSchema,
  updateCustomerIncomeSchema,
  upsertCustomerPreferencesSchema,
  upsertCustomerProfileSchema,
  uuidParamSchema,
} from '@kuberone/shared-validation';
