export {
  listWorkflowsQuerySchema,
  createWorkflowSchema,
  updateWorkflowSchema,
  workflowIdParamSchema,
  listTemplatesQuerySchema,
  createTemplateSchema,
  listExecutionsQuerySchema,
  listTriggersQuerySchema,
  createTriggerSchema,
  updateTriggerSchema,
  automationAnalyticsQuerySchema,
  listAutomationLogsQuerySchema,
  automationExportQuerySchema,
  automationAiSuggestSchema,
  emitTriggerSchema,
} from '@kuberone/shared-validation';
