export {
  autoVerifySchema,
  confirmUploadSchema,
  createDocumentDeficiencySchema,
  createDocumentRequestSchema,
  createDocumentTypeSchema,
  listDocumentDeficienciesQuerySchema,
  listDocumentRequestsQuerySchema,
  listDocumentTypesQuerySchema,
  listDocumentVersionsQuerySchema,
  listDocumentsQuerySchema,
  listOcrResultsQuerySchema,
  listVerificationResultsQuerySchema,
  presignUploadSchema,
  replaceDocumentSchema,
  runOcrSchema,
  scanDeficienciesSchema,
  updateDocumentDeficiencySchema,
  updateDocumentRequestSchema,
  updateDocumentTypeSchema,
  uploadDocumentSchema,
  uuidParamSchema,
  verifyDocumentSchema,
} from '@kuberone/shared-validation';
