export const UAT_QUALITY_GATES = {
  MAX_CRITICAL_DEFECTS: 0,
  MAX_HIGH_DEFECTS: 5,
  REQUIRED_SIGNOFFS: ['COMPLIANCE', 'MANAGEMENT', 'FINAL_UAT'] as const,
} as const;

export const UAT_BUSINESS_FLOWS = [
  'AUTH', 'CUSTOMER', 'DSA', 'LMS', 'LOS', 'DOCUMENT', 'REFERRAL',
  'COMMISSION', 'SUPPORT', 'CAMPAIGN', 'AI', 'ANALYTICS',
] as const;

export const UAT_USER_GROUPS = [
  'CUSTOMER', 'DSA_PARTNER', 'SALES_EXECUTIVE', 'RELATIONSHIP_MANAGER',
  'CREDIT_EXECUTIVE', 'OPERATIONS_EXECUTIVE', 'BRANCH_MANAGER', 'REGIONAL_MANAGER',
  'COMPLIANCE_OFFICER', 'MANAGEMENT', 'ADMIN',
] as const;

export const UAT_TEST_CASE_TYPES = [
  'POSITIVE', 'NEGATIVE', 'BOUNDARY', 'BUSINESS_RULE', 'EXCEPTION',
] as const;

export const UAT_SIGNOFF_TYPES = [
  'SALES', 'CREDIT', 'OPERATIONS', 'COMPLIANCE', 'MANAGEMENT', 'FINAL_UAT',
] as const;

export const UAT_DEFECT_SEVERITIES = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'] as const;

export const UAT_DEFECT_STATUSES = ['OPEN', 'ASSIGNED', 'FIXED', 'RETEST', 'CLOSED'] as const;
