export const SMS_MAX_RETRIES = 3;
export const SMS_RETRY_DELAY_MS = 30_000;

export const OTP_TEMPLATE_MAP: Record<string, string> = {
  LOGIN: 'LOGIN_OTP',
  REGISTER: 'REGISTRATION_OTP',
  VERIFY_MOBILE: 'MOBILE_VERIFICATION_OTP',
  PASSWORD_RESET: 'PASSWORD_RESET_OTP',
  KYC_AADHAAR: 'AADHAAR_OTP',
  CHANGE_MOBILE: 'MOBILE_VERIFICATION_OTP',
};

export const TRANSACTIONAL_SMS_EVENTS = new Set([
  'LOGIN_OTP',
  'APPLICATION_SUBMITTED',
  'APPLICATION_CREATED',
  'DOCUMENT_REQUESTED',
  'DOCUMENT_VERIFIED',
  'DOCUMENT_REJECTED',
  'SANCTION_ISSUED',
  'DISBURSEMENT_COMPLETED',
  'REFERRAL_CREATED',
  'REFERRAL_CONVERTED',
  'COMMISSION_APPROVED',
  'COMMISSION_PAID',
  'SUPPORT_TICKET_CREATED',
  'SUPPORT_TICKET_CLOSED',
]);

export const INDIAN_PHONE_REGEX = /^(\+91|91)?[6-9]\d{9}$/;
