/** CRM admin route permission map — mirrors routePermissions.tsx */
export const CRM_ROUTE_PERMISSIONS: Record<string, string[] | undefined> = {
  dashboard: undefined,
  leads: ['leads.read'],
  customers: ['customers.read'],
  applications: ['applications.read'],
  documents: ['documents.read'],
  products: ['products.read'],
  partners: ['partners.read'],
  referrals: ['referrals.read'],
  commissions: ['commissions.read'],
  notifications: ['notifications.read'],
  email: ['emails.read', 'notifications.read'],
  sms: ['sms.read', 'notifications.read'],
  whatsapp: ['notifications.read'],
  push: ['push.read', 'notifications.read'],
  campaigns: ['notifications.read'],
  automation: ['automation.read', 'automation.write', 'automation.analytics'],
  content: ['content.read', 'content.write', 'content.analytics'],
  support: ['tickets.read'],
  copilot: ['copilot.read', 'leads.read', 'applications.read', 'analytics.read'],
  analytics: ['analytics.read'],
  'executive-analytics': ['executive_analytics.read', 'analytics.read'],
  'branch-analytics': ['branch_analytics.read', 'analytics.read'],
  'regional-analytics': ['regional_analytics.read', 'analytics.read'],
  recommendations: ['recommendations.read', 'analytics.read'],
  knowledge: ['knowledge.read', 'knowledge.write', 'knowledge.manage'],
  rag: ['rag.read', 'rag.write', 'rag.manage'],
  'ai-platform': ['ai.read', 'ai.write', 'ai.manage'],
  users: ['users.read', 'roles.read'],
  governance: ['audit.read', 'compliance.read', 'risk.read', 'security.read'],
  audit: ['audit.read'],
  settings: ['settings.read'],
  'developer-portal': ['settings.read', 'audit.read'],
};

export const CRM_PROTECTED_ROUTES = Object.keys(CRM_ROUTE_PERMISSIONS);
