export const LOAN_PRODUCTS = [
  {
    slug: 'HOME_LOAN',
    name: 'Home Loan',
    variant: 'FRESH',
    icon: 'home',
    description: 'Finance your dream home with competitive rates',
    interestMin: 8.25,
    interestMax: 10.5,
    maxAmount: 50000000,
    features: ['Up to 30 years tenure', 'Balance transfer available', 'Tax benefits on interest'],
    documents: ['PAN', 'Aadhaar', 'Salary slips', 'Bank statements', 'Property papers'],
  },
  {
    slug: 'HOME_LOAN',
    name: 'Home Loan BT',
    variant: 'BT',
    icon: 'swap-horizontal',
    description: 'Transfer your existing home loan for better rates',
    interestMin: 8.0,
    interestMax: 9.75,
    maxAmount: 50000000,
    features: ['Lower EMI', 'Top-up option', 'Minimal documentation'],
    documents: ['Existing loan statement', 'PAN', 'Aadhaar', 'Property papers'],
  },
  {
    slug: 'HOME_LOAN',
    name: 'Home Loan Top-Up',
    variant: 'TOP_UP',
    icon: 'trending-up',
    description: 'Additional funding on your existing home loan',
    interestMin: 8.5,
    interestMax: 10.0,
    maxAmount: 20000000,
    features: ['Quick disbursal', 'No new property docs', 'Flexible usage'],
    documents: ['PAN', 'Aadhaar', 'Existing loan statement'],
  },
  {
    slug: 'LAP',
    name: 'Loan Against Property',
    variant: 'FRESH',
    icon: 'business',
    description: 'Unlock property value for personal or business needs',
    interestMin: 9.0,
    interestMax: 12.0,
    maxAmount: 25000000,
    features: ['High loan amount', 'Long tenure', 'Multi-purpose usage'],
    documents: ['PAN', 'Aadhaar', 'Property documents', 'Income proof'],
  },
  {
    slug: 'BUSINESS_LOAN',
    name: 'Business Loan',
    variant: 'WORKING_CAPITAL',
    icon: 'briefcase',
    description: 'Working capital and business expansion funding',
    interestMin: 11.0,
    interestMax: 16.0,
    maxAmount: 100000000,
    features: ['Unsecured options', 'Flexible repayment', 'Quick approval'],
    documents: ['PAN', 'GST', 'ITR', 'Bank statements', 'Business proof'],
  },
  {
    slug: 'AUTO_LOAN',
    name: 'Auto Loan',
    variant: 'FRESH',
    icon: 'car',
    description: 'New car financing with up to 90% on-road funding',
    interestMin: 8.75,
    interestMax: 11.5,
    maxAmount: 5000000,
    features: ['Up to 7 years tenure', 'Insurance bundled', 'Fast processing'],
    documents: ['PAN', 'Aadhaar', 'Salary slips', 'Quotation'],
  },
  {
    slug: 'EV_LOAN',
    name: 'EV Loan',
    variant: 'FRESH',
    icon: 'flash',
    description: 'Special rates for electric vehicles',
    interestMin: 7.99,
    interestMax: 10.0,
    maxAmount: 3000000,
    features: ['Green loan benefits', 'Subsidy eligible', 'Lower interest'],
    documents: ['PAN', 'Aadhaar', 'Income proof', 'EV quotation'],
  },
  {
    slug: 'USED_CAR_LOAN',
    name: 'Used Car Loan',
    variant: 'FRESH',
    icon: 'car-sport',
    description: 'Finance pre-owned cars up to 7 years old',
    interestMin: 10.5,
    interestMax: 14.0,
    maxAmount: 2500000,
    features: ['Up to 85% funding', '5 year tenure', 'Wide dealer network'],
    documents: ['PAN', 'Aadhaar', 'RC copy', 'Insurance', 'Valuation report'],
  },
  {
    slug: 'COMMERCIAL_VEHICLE_LOAN',
    name: 'Commercial Vehicle Loan',
    variant: 'FRESH',
    icon: 'bus',
    description: 'Finance trucks, buses, and commercial fleets',
    interestMin: 10.0,
    interestMax: 14.5,
    maxAmount: 15000000,
    features: ['Fleet discounts', 'Flexible EMI', 'Insurance support'],
    documents: ['PAN', 'GST', 'ITR', 'Business proof', 'Vehicle quotation'],
  },
] as const;

export type LoanProductConfig = (typeof LOAN_PRODUCTS)[number];
