export const COMMISSION_ENGINE_VERSION = '1.0.0';

export const LEDGER_NUMBER_PREFIX = 'KCL';
export const APPROVAL_NUMBER_PREFIX = 'KCA';
export const PAYMENT_NUMBER_PREFIX = 'KCP';
export const ADJUSTMENT_NUMBER_PREFIX = 'KCAD';
export const RECOVERY_NUMBER_PREFIX = 'KCR';

export const PARTNER_CODE_TO_COMMISSION_TYPE: Record<string, string> = {
  DSA: 'DSA',
  BUILDER: 'BUILDER',
  PROPERTY_DEALER: 'PROPERTY_DEALER',
  CA: 'CA',
  BROKER: 'BROKER',
  CORPORATE: 'CORPORATE',
  CHANNEL_PARTNER: 'CHANNEL_PARTNER',
  REFERRAL: 'CHANNEL_PARTNER',
};

export const DEFAULT_CURRENCY = 'INR';
